### ISSUE TITLE
Cannot perform a frozen installation because the lockfile needs updates

### ISSUE THREAD

**Issue by limaceous-bushwhacker** [hyoban/rss-to-bot#2]
ERR_PNPM_FROZEN_LOCKFILE_WITH_OUTDATED_LOCKFILE  Cannot perform a frozen installation because the lockfile needs updates

Note that in CI environments this setting is true by default. If you still need to run install in such cases, use "pnpm install --no-frozen-lockfile"
Error: Process completed with exit code 1.

https://github.com/hyoban/rss-to-bot/actions/runs/4542972434

**Comment by hyoban** [comment]
thanks, should work now
