### ISSUE TITLE
推送不了这个哎

### ISSUE THREAD

**Issue by pxd0207** [hyoban/rss-to-bot#3]
![image](https://user-images.githubusercontent.com/55773646/228725496-65b63248-627a-4cb6-b441-0fbbe18a0be8.png)

**Comment by hyoban** [comment]
部分 match 到的图片 url 可能需要特殊处理，实际发送时应该会 fallback 到发文字的

**Comment by Mikurations** [comment]
可是文字也没有哎

**Comment by hyoban** [comment]
> 可是文字也没有哎

它是直接让 action 失败了吗。如果方便的话，可以把你订阅的 rss 发我来帮你看看。

**Comment by Mikurations** [comment]
![image](https://user-images.githubusercontent.com/55773646/228754560-0dd9b23d-c2da-4152-b842-7055ee052d2c.png)
rss:：https://feeds.feedburner.com/toodaylab/4UvSDU55M3q

**Comment by hyoban** [comment]
抱歉现在才修复，应该可以用了
